In [4]:
from collections import namedtuple
import argparse
import os
import sys
import numpy as np
import torch
from torch import nn
from torch.autograd import Variable
from torch.utils.data.dataloader import DataLoader
from torch.utils.data import Dataset
from torch.utils.data.dataset import TensorDataset
import torch.nn.init as init
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence

In [5]:
import os
import torch
import numpy as np

class VocabularyIndexer(object):
    def __init__(self):
        self.word2idx = {}
        self.idx2word = []

    def add_word(self, word):
        if word not in self.word2idx:
            #print (word)
            self.idx2word.append(word)
            self.word2idx[word] = len(self.idx2word) - 1
        return self.word2idx[word]

    def __len__(self):
        return len(self.idx2word)


class MomentDescription(object):
    def __init__(self, path):
        self.dictionary = VocabularyIndexer()
        #print (os.path.join(path, 'description.txt'))
        self.train = self.tokenize(os.path.join(path, 'description.txt'))

    def tokenize(self, path):
        """Tokenizes a text file."""
        assert os.path.exists(path)
        # Add words to the dictionary
        with open(path, 'r') as f:
            tokens = 0
            for line in f:
                words = ['<eos>'] + line.split() + ['<eos>']
                tokens += len(words)
                for word in words:
                    if '.' in word:
                        word = word.replace(".", "")
                    self.dictionary.add_word(word)

        # Tokenize file content and returns the tokens
        with open(path, 'r') as f:
            ids = []
            token = 0
            for line in f:
                token = 0
                words = ['<eos>'] + line.split() + ['<eos>']
                sent = np.empty(shape=(len(words),), dtype =int)
                for word in words:
                    if '.' in word:
                        word = word.replace(".", "")
                    sent[token] = self.dictionary.word2idx[word]
                    token += 1
                ids.append(sent)
            
        return ids

In [6]:
def to_variable(tensor):
    if torch.cuda.is_available():
        tensor = tensor.cuda()
    return torch.autograd.Variable(tensor)


In [7]:
args = namedtuple('args', ['batch_size', 'wordcount', 'epochs', 'cuda', 'embedding_dim', 'hidden_dim', 'clip', 'num_layers'])(120, 7614+1, 10, True, 100, 100, 0.25, 1)

In [8]:
class LSTM(nn.Module):
    def __init__(self, args):
        super(LSTM, self).__init__()
        self.wordcount = args.wordcount
        self.embedding = nn.Embedding(num_embeddings=args.wordcount, embedding_dim=args.embedding_dim)
        self.embedding.weight.data.uniform_(-0.8, 0.8)
        self.lstm1 = nn.LSTM(input_size=args.embedding_dim, num_layers=args.num_layers, hidden_size=args.hidden_dim)
        for name, param in self.lstm1.named_parameters():
            if 'bias' in name:
                init.constant(param, 0.0)
            elif 'weight' in name:
                init.uniform(param, -0.8, 0.8)
        self.projection = nn.Linear(in_features=args.hidden_dim, out_features=args.wordcount)
        self.projection.weight = self.embedding.weight

    def forward(self, input,lengths, stochastic=False):
        #print (type(input.data()))
        embeddings = self.embedding(input)
        packed = pack_padded_sequence(embeddings, lengths)
        h_t, c_t = self.lstm1(packed)
        
        output, _ = pad_packed_sequence(h_t)
        output = self.projection(output)
        return output


In [9]:
class CrossEntropyLoss3D(nn.CrossEntropyLoss):
    def forward(self, input, target):
        return super(CrossEntropyLoss3D, self).forward(input.view(-1, input.size()[2]), target.view(-1))

In [10]:
def make_pad(X,m):
    padded_samples = []
    for s in X:
        k = m - s.shape[0]
        x = np.zeros(k)
        s = np.append(s,x)
        #print (s)
        padded_samples.append(s)
    return np.array(padded_samples, dtype = int)


def get_lengths(X):
    lens = []
    for sample in X:
        lens.append(len(sample))
    return lens
    

def get_maxlen(X):
    s = 0
    sample1 = X[0]
    for sample in X:
        if s < len(sample):
            s = len(sample)
            sample1 = sample
    #print ("longest sample",sample1)      
    return s

def torchify(a,b,c):
    a = torch.LongTensor(a).contiguous()
    a = torch.transpose(a, 0, 1)
    b = torch.LongTensor(b).contiguous()
    b = torch.transpose(b, 0, 1)
    #print ("c - label", c)
    #c = torch.IntTensor(c)
    #print ("c - label", c)
   
    return a,b,c


def my_collate(batch):
    batch = sorted(batch, key=lambda x: x.shape[0], reverse=True)
    batch_size = len(batch)
    max_len = get_maxlen(batch)
    X = []
    Y = []
    
    for x in batch:
        X.append(x[:-1])
        Y.append(x[1:])
        
    print (np.array(X).shape)
    print (np.array(Y).shape)
    print ("......")
    X = np.array(X)
    lens = np.array(get_lengths(X))
    padX = make_pad(X,max_len)
    Y = np.array(Y)
    padY = make_pad(Y, max_len)
    #print ("before torchify", padX)
    padX, padY, lens = torchify(padX, padY, lens)
    #print ("......")
    #print ("first sample",(padX[0]))
    #print ("x",X)
    #print ("y",Y)
    #print ("after torchify", padX)
    print ("before train",padX.shape)
    print ("before train",padY.shape)
    return padX, padY, lens 


        

In [11]:
class LSTMDataset(Dataset):

    def __init__(self, path):
        self.path = path 
        desc = MomentDescription(self.path)
        self.train = desc.train
        


    def __len__(self):
        return len(self.train)

    def __getitem__(self, idx):
        return self.train[idx]


In [24]:
def train_model(no_epoch, model, optimizer, criterion, train_loader):
    for epoch in range(no_epoch):  # number of epochs to perform
        running_loss = 0.0
        for i, data in enumerate(train_loader, 0):
            X, Y, lens = data
            #print("XxxXXXXXXxxxx", X.shape)
            X = to_variable(X)
            Y = to_variable(Y)
            optimizer.zero_grad()
            # forward + backward + optimize
            print (lens)
            outputs = model(X, lens)
            print ("after forward",outputs.shape)
            print ("after forward",Y.shape)
            print (Y)
            #loss = criterion(outputs, Y)
            #loss.backward()
            #torch.nn.utils.clip_grad_norm(model.parameters(), args.clip)
            optimizer.step()

            # print statistics
            #running_loss += loss.data[0]
            #if i%50 == 0:
            #    print('[%d, %5d] loss: %.3f' % (epoch + 1, i + 1, running_loss))
            #running_loss = 0.0 
        model_name = 'model'+str(epoch)+'.pkl'
        torch.save(model.state_dict(), model_name)
    print('Finished Training')

In [ ]:

def main():
    no_epochs = 10
    model = LSTM(args)
    #model.cuda()
    '''
    filePath = "/home/ubuntu/hw3/notebook/"+"hw3_train9.pkl"
    model_lstm = (torch.load(filePath))
    model.load_state_dict(model_lstm)
    '''
    path = ''
    train = LSTMDataset(path)
    train_loader = DataLoader(train, batch_size=6, shuffle=True, collate_fn = my_collate)
    criterion = CrossEntropyLoss3D()
    optimizer = torch.optim.SGD(model.parameters(), lr=25)
    train_model(no_epochs, model, optimizer, criterion, train_loader)

if __name__ == '__main__':
    main()


(6,)
(6,)
......
before train torch.Size([17, 6])
before train torch.Size([17, 6])
[16 10  9  8  8  4]
after forward torch.Size([16, 6, 7615])
after forward torch.Size([17, 6])
Variable containing:
  797    25   341    25    50    60
  223    57   148    91   490   214
   24   263   560    92   152   627
  249   246    25    89  3975     0
   74   426   249    55    58     0
 1972   824    74    74   847     0
  367    37    25   308   458     0
   66    25   686     0     0     0
   23   552     0     0     0     0
   58     0     0     0     0     0
   50     0     0     0     0     0
  963     0     0     0     0     0
   23     0     0     0     0     0
   28     0     0     0     0     0
  249     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 17x6]

(6,)
(6,)
......
before train torch.Size([14, 6])
before train torch.Size([14, 6])
[13 12 11 10  8  7]
after forward torch.Size([13, 6, 7615])
after forward 

after forward torch.Size([16, 6, 7615])
after forward torch.Size([17, 6])
Variable containing:
   25   215    25    50    25     1
   72   370   376   397   883   223
 2824  2915    74   188    24  1015
   18  4135    25    58   355    66
    8     5   111   796  1277   126
   82    25  2685     1   127     0
    1  1058   816   438   363     0
  797   305   817     0     0     0
 5264     7     0     0     0     0
   58  1412     0     0     0     0
   25     0     0     0     0     0
  305     0     0     0     0     0
   74     0     0     0     0     0
   25     0     0     0     0     0
  408     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 17x6]

(6,)
(6,)
......
before train torch.Size([13, 6])
before train torch.Size([13, 6])
[12 10  6  5  5  5]
after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
   25     1    62    21   139  3823
 1575    21   324  3399   

after forward torch.Size([9, 6, 7615])
after forward torch.Size([10, 6])
Variable containing:
   25     1    85    25    25   341
  148    62   273   438    60   560
 1197    51    25     4  3951   110
   25    25   514   348    14     0
   85   376    81     1  1312     0
  227    74    25   662     0     0
   66    25    57     0     0     0
 1069   865     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 10x6]

(6,)
(6,)
......
before train torch.Size([17, 6])
before train torch.Size([17, 6])
[16 11  9  8  7  6]
after forward torch.Size([16, 6, 7615])
after forward torch.Size([17, 6])
Variable containing:
    1  1440    96    25    50    25
    3    67   214     7  3074   673
   73   151   402   324   305  5131
   33   374    18    17    58   198
   74   998    14    25    25    60
    1    37    24   148   687     0
  295     1    25  1689     0     0
    8    71   782     0     0     0
   19   456     0     0    

after forward torch.Size([16, 6, 7615])
after forward torch.Size([17, 6])
Variable containing:
  189   148  3434   116   401  2256
   18  1197   257  6675    14    14
  370   341  1780   522  7269   148
 5472   560   110  1412    70   817
 3857    62    81   188  3551     0
  480   199   148     0     0     0
   81   380  1197     0     0     0
   25    24     0     0     0     0
  148   249     0     0     0     0
 1197    74     0     0     0     0
   37    50     0     0     0     0
  317     0     0     0     0     0
   58     0     0     0     0     0
   25     0     0     0     0     0
  188     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 17x6]

(6,)
(6,)
......
before train torch.Size([14, 6])
before train torch.Size([14, 6])
[13  8  7  6  6  6]
after forward torch.Size([13, 6, 7615])
after forward torch.Size([14, 6])
Variable containing:
    1    67    12     1  1737    50
   36   688  4907    46   

after forward torch.Size([15, 6])
Variable containing:
    1  1448    25    91  1490    46
   46    70    50   241    89    39
   24    50     4  6808   112  2009
    1    18   152   536    11     0
  139   832    25  3587  1742     0
  190   413   552   817   193     0
   87    28    58     0     0     0
   52    58     1     0     0     0
  101   458    46     0     0     0
   24   177     0     0     0     0
  249    24     0     0     0     0
   74    60     0     0     0     0
   52     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 15x6]

(6,)
(6,)
......
before train torch.Size([25, 6])
before train torch.Size([25, 6])
[24 10  9  8  8  6]
after forward torch.Size([24, 6, 7615])
after forward torch.Size([25, 6])
Variable containing:
   25    25  1412    25    50  5082
  587  4397  2375  1079   397  5468
   44    24    70     4   188  1249
   25   139  1864    17    58   152
  321   702   305    25   796 

after forward torch.Size([11, 6, 7615])
after forward torch.Size([12, 6])
Variable containing:
   25     1    25     1    46   423
   21  2925    62    21   100   311
  100   769    24    14    57    17
   25    14   370   137    24     0
 2691  1287   151     1  1650     0
  112    17    25   189     0     0
   81    14  1362  1826     0     0
   25   257   412     0     0     0
  148     0     0     0     0     0
 1197     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 12x6]

(6,)
(6,)
......
before train torch.Size([12, 6])
before train torch.Size([12, 6])
[11 10  9  8  6  5]
after forward torch.Size([11, 6, 7615])
after forward torch.Size([12, 6])
Variable containing:
   42  1448    25  1440   299     1
   32   181   107    62   300   388
   24    55   108   101   363    14
   18  1718   273    41   165   257
  727    74     1   407   221     0
   37   182   320    25     0     0
  376    18    74   242   

after forward torch.Size([11, 6, 7615])
after forward torch.Size([12, 6])
Variable containing:
   62    25    25    91    62    50
   24   256  7445   652    24   148
   63     4    94   536  1125   353
  721    58    95   817     2    58
  584  3699    81    37   190   198
  312    18    25    25  2630  3018
  144     8   148    60    41     0
   70  6638  1197   390     0     0
  651     0     0     0     0     0
  101     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 12x6]

(6,)
(6,)
......
before train torch.Size([12, 6])
before train torch.Size([12, 6])
[11 10 10  7  7  4]
after forward torch.Size([11, 6, 7615])
after forward torch.Size([12, 6])
Variable containing:
    1  1115    25    67     1   686
  423   815    50  3241   297   522
   74   560   397   401   439    50
  346    62    58    70   486     0
  349    24    25   651    44     0
  424   139   223   101    52     0
   18   190   997     0   

after forward torch.Size([14, 6, 7615])
after forward torch.Size([15, 6])
Variable containing:
   62     1    25  3975    25    85
 1398    21   110   144    62   148
  214    24  4323    17    14   353
   24   355     1    37   148   935
   66    19  1750    23  2405     0
  101    55   629   550     0     0
   37    74  4324     0     0     0
  633   256  4086     0     0     0
   18    58     0     0     0     0
  925    25     0     0     0     0
   58   305     0     0     0     0
 1453     0     0     0     0     0
   28     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 15x6]

(6,)
(6,)
......
before train torch.Size([17, 6])
before train torch.Size([17, 6])
[16 12  8  7  5  5]
after forward torch.Size([16, 6, 7615])
after forward torch.Size([17, 6])
Variable containing:
 1440    25   797  1224    21   261
   36    50  1939   148   353   883
   24   397    74   584   354    16
  189   152   234  6091  6

after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
   21    22  1125    21    25    36
   70    25   584    24   299    24
   25  5239    25   355     4   149
  167  5240   570   125   363   511
  178   560   152    20     1   190
  782     1   305   152  1339  4693
 2861  5241    58    21   209   156
   70  1166   188   139     0     0
  509    25   636     0     0     0
  305   916   407     0     0     0
    7     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 13x6]

(6,)
(6,)
......
before train torch.Size([13, 6])
before train torch.Size([13, 6])
[12  9  7  6  6  6]
after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
   21    25   166   308    25   148
   24    36    24    74    50  1197
    1    24   139   399   174    62
 3527  6594    14    14   125   688
   48   993   817   257   305   112
   18    52  1686     0   

before train torch.Size([13, 6])
before train torch.Size([13, 6])
[12 11 11 11  6  6]
after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
   25    21    25    46    72     1
  971   174    50    24    69    46
   62   367   445   297    70  1198
  335    67    24   356   698    25
   58    37    37    19    71   793
  735   374    25    17     0     0
    1   673    45    18     0     0
  513    24   219   240     0     0
   70     1   374    37     0     0
    1  3464  1308   419     0     0
   50     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 13x6]

(6,)
(6,)
......
before train torch.Size([10, 6])
before train torch.Size([10, 6])
[9 8 7 5 5 1]
after forward torch.Size([9, 6, 7615])
after forward torch.Size([10, 6])
Variable containing:
   62    36    25  2396    57     0
   37   367   221   770   148     0
  261  1020   125    14    43     0
  688   152    55  

after forward torch.Size([9, 6, 7615])
after forward torch.Size([10, 6])
Variable containing:
 1744    25    25    25  1386     1
  198    62    62  5207  1012  2648
   28  1686   367   702   536   781
   58   100   246    58  2405     0
  458    66    25   104     0     0
  200   312   242     0     0     0
 1745     7     0     0     0     0
 1746   112     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 10x6]

(6,)
(6,)
......
before train torch.Size([13, 6])
before train torch.Size([13, 6])
[12 11 10  9  7  7]
after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
  221     1    62    42    21    25
 1848    62    70   310    70  4772
 1510   296   189  2449   189   750
  363   246  1294     5   190    33
   62     1    19   308  1588    25
   24   797    24    81  3084  2094
    1  2342   249   148     0     0
   63    76    74  1197     0     0
   14   538  3033     0    

before train torch.Size([16, 6])
[15 12 10  8  7  6]
after forward torch.Size([15, 6, 7615])
after forward torch.Size([16, 6])
Variable containing:
 1469   228    21  1503     1    25
   62   997  1029    70    62  3253
   24    70  1685   276    73  1377
   25   509    17  1398    37    58
  286    56    18   289    25    92
 1057    14   112     5  6080     0
   82   817    24   308     0     0
   66   127  5445     0     0     0
   57    58  5446     0     0     0
   37    25     0     0     0     0
   58    50     0     0     0     0
   25     0     0     0     0     0
 1470     0     0     0     0     0
  621     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 16x6]

(6,)
(6,)
......
before train torch.Size([17, 6])
before train torch.Size([17, 6])
[16 14 11  9  7  5]
after forward torch.Size([16, 6, 7615])
after forward torch.Size([17, 6])
Variable containing:
 2540   341    25    25    72   297
   62  16

after forward torch.Size([10, 6, 7615])
after forward torch.Size([11, 6])
Variable containing:
   36    25    50  3987    57  1083
   70   652   445   883   440   593
 1128   339    24   494    58  6426
 5050  4820     8   112  4238  1021
    2    40    55   592    81    74
  373    41    37    25     1  2454
   14    24  1937   552   344     0
  148    25   458     0     0     0
  817   301     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 11x6]

(6,)
(6,)
......
before train torch.Size([11, 6])
before train torch.Size([11, 6])
[10 10  9  8  7  7]
after forward torch.Size([10, 6, 7615])
after forward torch.Size([11, 6])
Variable containing:
    1    25   294    62    62    91
   62    50  1125    24  2556    92
  240   702  3334   297   737   267
   37    58    18   901  2711     5
    1   697    71    14     5   642
  730    24  1125    24  1690   299
   70    37   267  1412     0     0
   91    25  2634     0   

after forward torch.Size([13, 6, 7615])
after forward torch.Size([14, 6])
Variable containing:
 2109    21    21   502  1485  3020
 1339    24   237    14    46   367
  126   139   110  1386    87   370
  305    63    14    62    40     0
   24   367  3864    24    50     0
  249    58    58    25     0     0
   74    25    50  1412     0     0
   25   188     0     0     0     0
   50  1275     0     0     0     0
 1249   174     0     0     0     0
  152     0     0     0     0     0
  308     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 14x6]

(6,)
(6,)
......
before train torch.Size([12, 6])
before train torch.Size([12, 6])
[11 10 10  8  4  4]
after forward torch.Size([11, 6, 7615])
after forward torch.Size([12, 6])
Variable containing:
    1    25    67    42    50    45
   36    50  3494   148    14    14
    4   987    37  1248   817   257
  152    37   651   112     0     0
  277     1   101   152   

after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
 1448    36    25     1  4265    92
   24    37   346   797    14    89
  189   188   765  2925    24    28
  190   688    94   256    66     1
   69    17    95    24   188   259
  980  1686  2163    25     7     0
   70    40   670   234     0     0
    1    36    24     0     0     0
  778    37    25     0     0     0
   74   305  1412     0     0     0
 1590     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 13x6]

(6,)
(6,)
......
before train torch.Size([11, 6])
before train torch.Size([11, 6])
[10  9  9  8  8  5]
after forward torch.Size([10, 6, 7615])
after forward torch.Size([11, 6])
Variable containing:
  108    25     1  1211     1    25
   24  2184   689  1922   438   346
   60    37  2207    70     4   828
  688    25    25  2561   363    17
   40  1199   308    14    37     0
   50    14    81   148   

after forward torch.Size([13, 6, 7615])
after forward torch.Size([14, 6])
Variable containing:
    1   166     1    25  1060    25
  166    70     7    62  1081    31
 2501    60    70    19   637   402
   24   408     1  2755    70    33
  189    14   937    25  2047     0
  486  1686   627    50     0     0
   24   817     0     0     0     0
  249   499     0     0     0     0
   74  6544     0     0     0     0
   25   305     0     0     0     0
  165   673     0     0     0     0
 2159     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 14x6]

(6,)
(6,)
......
before train torch.Size([18, 6])
before train torch.Size([18, 6])
[17  9  8  8  7  7]
after forward torch.Size([17, 6, 7615])
after forward torch.Size([18, 6])
Variable containing:
   25    50    62    25    62   645
  166   148   178   177  1548   259
   24   125   187   702    11  5407
   25    58    58  1092  5556    58
  139    25   376    58   

after forward torch.Size([14, 6, 7615])
after forward torch.Size([15, 6])
Variable containing:
    1    62    25   177    21  2707
   21    24    50   400   880    14
  137  1125  1353    66  1168  2201
    1  1314    37   101     1  7197
  139   190    25  5124   513    63
 7126   362   983     0     0     0
  310   363     0     0     0     0
    5     0     0     0     0     0
  308     0     0     0     0     0
   18     0     0     0     0     0
   19     0     0     0     0     0
  592     0     0     0     0     0
 3285     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 15x6]

(6,)
(6,)
......
before train torch.Size([14, 6])
before train torch.Size([14, 6])
[13  9  8  7  7  7]
after forward torch.Size([13, 6, 7615])
after forward torch.Size([14, 6])
Variable containing:
    1   341    92    62    60  6561
   21   815   536    24  2637   988
  137   560   499   355  1838   148
  297    25   152   253   

after forward torch.Size([13, 6, 7615])
after forward torch.Size([14, 6])
Variable containing:
   25    62  7547     1   341   341
   21    82  5630   797   560   560
 1588    66   536  1196    25   256
   25     7  1686   370   399    74
 3084    33   817  1125    18   821
  125    66  1486   815     8   148
 1796  1634    25   816    25  1197
   33    18   153   817   193     0
  256    39     0     0     0     0
   58     0     0     0     0     0
 3863     0     0     0     0     0
  305     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 14x6]

(6,)
(6,)
......
before train torch.Size([11, 6])
before train torch.Size([11, 6])
[10  9  8  6  5  5]
after forward torch.Size([10, 6, 7615])
after forward torch.Size([11, 6])
Variable containing:
    1    62     1    50    67   370
  355    70     2   445   367    71
 2205   779  3558    20   105   522
  367    82   627   152    50  1412
  374     1    37   600   

after forward torch.Size([11, 6, 7615])
after forward torch.Size([12, 6])
Variable containing:
   91     1    62    25    42   108
 2112  1653   311   248   367   311
 1623   917    17   144    66  3018
  651    14   152    24    23  5221
   74  1630  1101   507    37  1197
  509   305   246  1045    50     0
    7   673    81  1046     0     0
  246    17   148     0     0     0
  509   641  1197     0     0     0
 3030     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 12x6]

(6,)
(6,)
......
before train torch.Size([14, 6])
before train torch.Size([14, 6])
[13  9  7  7  6  6]
after forward torch.Size([13, 6, 7615])
after forward torch.Size([14, 6])
Variable containing:
 2793     1    67    25    25    11
  310    62  1212    21  2164   971
   24   122   651  1168    14    62
  152    41   101  1310  1848  3638
  305     5    37    14  2141    84
   74     1   543   257     0     0
 1412  2407     0     0   

after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
  341     1    25     1  2107   633
  560   177    21    62    92  6725
   25    24   702   196    89   581
   99     1    58    17    90   112
   37   189   996    91   812     0
   25   190    17  1804     0     0
  305   754    25     0     0     0
   74    66   393     0     0     0
   25   148     0     0     0     0
 3961  1315     0     0     0     0
 2882     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 13x6]

(6,)
(6,)
......
before train torch.Size([13, 6])
before train torch.Size([13, 6])
[12  7  6  5  5  3]
after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
    1    25   971    62   108  2694
  355   177    62   130    39  4335
  299   584   133  1291    70     0
  486     1    37    17   121     0
  363   139    56     0     0     0
   24   239     0     0   

after forward torch.Size([15, 6, 7615])
after forward torch.Size([16, 6])
Variable containing:
    1    25    62    25    67   101
  107    92   402    50    39   536
   36  1304    25   688    58  2725
   24    24   411    40    50     0
    1   521   101    25     0     0
  189   289    17   378     0     0
  190    58     0     0     0     0
   18     1     0     0     0     0
  234   394     0     0     0     0
  520     0     0     0     0     0
   19     0     0     0     0     0
  407     0     0     0     0     0
   25     0     0     0     0     0
  165     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 16x6]

(6,)
(6,)
......
before train torch.Size([9, 6])
before train torch.Size([9, 6])
[8 8 8 8 7 6]
after forward torch.Size([8, 6, 7615])
after forward torch.Size([9, 6])
Variable containing:
  148   341    25    25    25   148
 1197   148   438    50    50  1197
 1143   560  3394   397   169     7


after forward torch.Size([10, 6, 7615])
after forward torch.Size([11, 6])
Variable containing:
   62    25  2017   148     1    92
  670   107   321   127    21   148
  239   435   134    17   277   480
   37    39    66    74   191     0
  307    58   101   107   101     0
   81    25    76    36     0     0
   25  1310   721     0     0     0
  148     0     0     0     0     0
 1197     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 11x6]

(6,)
(6,)
......
before train torch.Size([13, 6])
before train torch.Size([13, 6])
[12  8  8  7  6  5]
after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
   25     1    62   228   148    25
   50   119    54   191   308    67
  397   373    41   509    74   240
  152   332    55    56    12   112
   25     5    74     5   221     0
  322    25    66   308     0     0
   58  2386  1957     0     0     0
   25     0     0     0   

after forward torch.Size([18, 6, 7615])
after forward torch.Size([19, 6])
Variable containing:
  228    25   341    25     1   177
   14    62   838    62    21   272
 1113    24   188    24  1410   374
   58    25    58    25    40   431
   11   149   560   370     1     0
 1114   190     1   287  1940     0
  398   191    45   688     0     0
  880    66   305    58     0     0
  348   404    24    66     0     0
  110   526   249   188     0     0
   25    66     0     0     0     0
   25   126     0     0     0     0
   50     0     0     0     0     0
  104     0     0     0     0     0
  292     0     0     0     0     0
   25     0     0     0     0     0
  110     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 19x6]

(6,)
(6,)
......
before train torch.Size([13, 6])
before train torch.Size([13, 6])
[12  8  8  7  6  6]
after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable co

after forward torch.Size([19, 6, 7615])
after forward torch.Size([20, 6])
Variable containing:
   46  1440    62   139  1386   970
   24    72   367   299   851    14
  189  2078    66  1198    14  2405
  196    40    56  1412   817     0
 1375    41    18     0     0     0
 2275   791   688     0     0     0
   55     1    40     0     0     0
  592   241   187     0     0     0
  188   698     0     0     0     0
   74     0     0     0     0     0
 1412     0     0     0     0     0
    8     0     0     0     0     0
  981     0     0     0     0     0
  187     0     0     0     0     0
   23     0     0     0     0     0
   58     0     0     0     0     0
   52     0     0     0     0     0
  145     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 20x6]

(6,)
(6,)
......
before train torch.Size([17, 6])
before train torch.Size([17, 6])
[16 16 10  8  7  6]
after forward torch.Size([16, 6, 7615])
after for

after forward torch.Size([21, 6, 7615])
after forward torch.Size([22, 6])
Variable containing:
 2961     1   108   341   107    42
   74    57    24   815    36    73
    1    73    25   560   148    33
   62     5    60   149   367  2280
   70     1   190  3253    28     0
    1   744  1916     0     0     0
  139    18    25     0     0     0
   18   353    61     0     0     0
   60   935     0     0     0     0
 2962     0     0     0     0     0
  310     0     0     0     0     0
    5     0     0     0     0     0
 1412     0     0     0     0     0
   37     0     0     0     0     0
   25     0     0     0     0     0
  188     0     0     0     0     0
  673     0     0     0     0     0
   74     0     0     0     0     0
   25     0     0     0     0     0
  504     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 22x6]

(6,)
(6,)
......
before train torch.Size([16, 6])
before train torch.Size([16, 6

after forward torch.Size([13, 6, 7615])
after forward torch.Size([14, 6])
Variable containing:
    1    25   341    25    50   148
   45  4963   148  1340  1686   538
  310   125   560   148   367  3168
    5   374    91  2544   592   536
  308   126  5266  2405   429   817
  219    25   377     0     0     0
   25   148     0     0     0     0
   50  1197     0     0     0     0
  397     0     0     0     0     0
   58     0     0     0     0     0
   25     0     0     0     0     0
  188     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 14x6]

(6,)
(6,)
......
before train torch.Size([16, 6])
before train torch.Size([16, 6])
[15 11  7  7  5  5]
after forward torch.Size([15, 6, 7615])
after forward torch.Size([16, 6])
Variable containing:
   25   341   337    36    62    62
   50   560  1017    24  2879   310
  308    25    18   189  5483     5
  367   423     1  1007   199   308
  152   277    62    14   

after forward torch.Size([13, 6, 7615])
after forward torch.Size([14, 6])
Variable containing:
  341   341    21    60  1211   385
  815   148  1686  3372  6883    50
 1520   560   419   148   148    14
  560   223   200   310  1546  2222
 2859    24   388     5    66    24
 3815   139     5   308   126     0
   74  1389   583     0     0     0
   25    40     0     0     0     0
   62  6533     0     0     0     0
   24     0     0     0     0     0
 3085     0     0     0     0     0
 3542     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 14x6]

(6,)
(6,)
......
before train torch.Size([11, 6])
before train torch.Size([11, 6])
[10  8  8  7  7  5]
after forward torch.Size([10, 6, 7615])
after forward torch.Size([11, 6])
Variable containing:
   25   308    25  1139   228  2460
  148   169  1694   754   615  1084
   60     1    25    23   324    74
 1084  1125  2546  1140    17  6856
   14  1343  4709    37   

after forward torch.Size([14, 6, 7615])
after forward torch.Size([15, 6])
Variable containing:
 1211  2795    21    91     1    25
   25  1398    14    92  6124   653
   21  2709   830   515   698   794
   24    58   411    86    14  3593
   12  1196   264   101  2405     0
  148   189  1922     0     0     0
   82  1398     0     0     0     0
    1     0     0     0     0     0
  992     0     0     0     0     0
 1840     0     0     0     0     0
   58     0     0     0     0     0
   25     0     0     0     0     0
   50     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 15x6]

(6,)
(6,)
......
before train torch.Size([14, 6])
before train torch.Size([14, 6])
[13 10  9  8  6  4]
after forward torch.Size([13, 6, 7615])
after forward torch.Size([14, 6])
Variable containing:
   25     7  1961    25   139    25
   50   125    25    50  4215    72
  440    63  2730     4    24  1324
 3087    55    74  3458   

after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
    1     1    85  1632  3557   148
   46   598    51   272    85    50
  815    14    81  1329  5068  1084
  816   817    25    33    46     0
  817    24    50   282     0     0
   40    25     0     0     0     0
  200   301     0     0     0     0
   74     0     0     0     0     0
   25     0     0     0     0     0
  143     0     0     0     0     0
  311     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 13x6]

(6,)
(6,)
......
before train torch.Size([11, 6])
before train torch.Size([11, 6])
[10  9  8  8  7  4]
after forward torch.Size([10, 6, 7615])
after forward torch.Size([11, 6])
Variable containing:
    1    25    46    62    25  2877
    7  2112   196   735    62   536
   86   589   331   305   253  2405
    1    52    70     7    25     0
  355   431   651    55    46     0
  295     5    52    74   

after forward torch.Size([16, 6, 7615])
after forward torch.Size([17, 6])
Variable containing:
    1     1    25    25  1639    61
  388  3373  1207   177    99   199
  137   633  2198    49  3652   219
    1  2179    37    40    70   187
 7200  3374    25    25   370   413
 4153    60  4204    50     0     0
 1081    58   276     0     0     0
   25   370     0     0     0     0
 1412    37     0     0     0     0
  152    25     0     0     0     0
   25   188     0     0     0     0
 2767     0     0     0     0     0
  305     0     0     0     0     0
    7     0     0     0     0     0
  916     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 17x6]

(6,)
(6,)
......
before train torch.Size([18, 6])
before train torch.Size([18, 6])
[17 12 10  8  6  5]
after forward torch.Size([17, 6, 7615])
after forward torch.Size([18, 6])
Variable containing:
    1     1    25   148    25  1125
  900   261    57  1197  4

after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
    1    25    46    25    62    91
   21   189   125     7  1198   248
   70   214    58   367    25   879
 4183    14    95    37   504   101
  373  2405   673    25     0     0
  311    24    74  1125     0     0
   24  3085    62     0     0     0
  249  3542     0     0     0     0
   74     0     0     0     0     0
   25     0     0     0     0     0
   50     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 13x6]

(6,)
(6,)
......
before train torch.Size([19, 6])
before train torch.Size([19, 6])
[18 12 11 10  7  6]
after forward torch.Size([18, 6, 7615])
after forward torch.Size([19, 6])
Variable containing:
   62    25   435   108    25    71
   70    67   144   688  1207  3307
  381   324   582    24   148     4
 2750    17    94     1   310     5
   24   845    95  4527     5   637
   66    18    18    81   

[9 8 7 7 5 4]
after forward torch.Size([9, 6, 7615])
after forward torch.Size([10, 6])
Variable containing:
  341    46   560    25   838    67
  148    19  4876  1370    58  1017
  560   592    74   218    25   145
   25   242   189    25   305     0
  166    18  2116  1067     0     0
   86    19  1398  1068     0     0
    1    20     0     0     0     0
   50     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 10x6]

(6,)
(6,)
......
before train torch.Size([19, 6])
before train torch.Size([19, 6])
[18 13  9  7  6  5]
after forward torch.Size([18, 6, 7615])
after forward torch.Size([19, 6])
Variable containing:
 1440     1    92    50   203    25
   62     7    86   397     7    50
   70   815   189   188  3241  1687
    1   816   984    58    12   218
  189   817   515     1   846     0
  559  1588    55   523     0     0
   43    25    74     0     0     0
  407    85   504     0     0     0
    1    81  

before train torch.Size([22, 6])
before train torch.Size([22, 6])
[21 13 11 11  4  4]
after forward torch.Size([21, 6, 7615])
after forward torch.Size([22, 6])
Variable containing:
 1115    62   148  1339  2939   467
  815   137   299   126    43   402
  560   355   486   627    20   126
    1   190    28    24     0     0
   60    19    25  1639     0     0
   18  1301   531    74     0     0
  139    21    18  1412     0     0
 2116   354    55  1686     0     0
 1530    24    74     8     0     0
  480   249   308  1249     0     0
   24    74     0     0     0     0
   25   322     0     0     0     0
  188     0     0     0     0     0
  238     0     0     0     0     0
  916     0     0     0     0     0
   18     0     0     0     0     0
  104     0     0     0     0     0
  105     0     0     0     0     0
 1639     0     0     0     0     0
  256     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 2

before train torch.Size([16, 6])
before train torch.Size([16, 6])
[15 11  8  8  7  7]
after forward torch.Size([15, 6, 7615])
after forward torch.Size([16, 6])
Variable containing:
    1  1069   108    25    21    25
   21    57   183  5783   490   148
   37   243   189    74   246  1412
   25    25    81    25    25    70
  624   107    25   322    60  1386
   51  1067   148    14   190   317
  112    44  1197  2405     0     0
   18    25     0     0     0     0
  272   148     0     0     0     0
   41  1197     0     0     0     0
   18     0     0     0     0     0
  100     0     0     0     0     0
  187     0     0     0     0     0
   23     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 16x6]

(6,)
(6,)
......
before train torch.Size([12, 6])
before train torch.Size([12, 6])
[11 10  5  5  5  4]
after forward torch.Size([11, 6, 7615])
after forward torch.Size([12, 6])
Variable containing:
   25     1 

after forward torch.Size([11, 6, 7615])
after forward torch.Size([12, 6])
Variable containing:
  341    25    50    25   148     1
  560    50   445    62    60   116
  228   125    24   273  3216   149
  906   188   127    17    14   834
   25    58    17    66   817   768
  307   228    37   101     0     0
   81   212    67     0     0     0
   25     0     0     0     0     0
  148     0     0     0     0     0
 1197     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 12x6]

(6,)
(6,)
......
before train torch.Size([19, 6])
before train torch.Size([19, 6])
[18 13 13  9  7  6]
after forward torch.Size([18, 6, 7615])
after forward torch.Size([19, 6])
Variable containing:
   25   148     1   341  3671   697
   50  1197   423  1301    74    24
  397   341    74     1    21    37
  305   560  1900   139    14    25
   58    25  2733   439   148  1674
  796   108   213    37   817     0
 3285  1243   509    25   

(6,)
(6,)
......
before train torch.Size([12, 6])
before train torch.Size([12, 6])
[11  9  7  6  5  5]
after forward torch.Size([11, 6, 7615])
after forward torch.Size([12, 6])
Variable containing:
 1550    25   341    25   108    25
   86    36   148   148    43  6427
   60    82   560   204    37    16
  138    25    25   486   256  3458
    4   312   846   363     0     0
   28   152   768     0     0     0
   36    25     0     0     0     0
   86   223     0     0     0     0
  370     0     0     0     0     0
  138     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 12x6]

(6,)
(6,)
......
before train torch.Size([11, 6])
before train torch.Size([11, 6])
[10 10  8  6  6  5]
after forward torch.Size([10, 6, 7615])
after forward torch.Size([11, 6])
Variable containing:
   25   223  1518  1478   344   686
 1125    43    82   453    72    14
  791     1  1169    95   310  1232
   25  1504    70  1907     9  

before train torch.Size([16, 6])
[15 13 10  7  5  5]
after forward torch.Size([15, 6, 7615])
after forward torch.Size([16, 6])
Variable containing:
   25    25   148    62    21   107
  426    62   697    51    24    36
  572    24    24    17   282   584
 6582    25    37   592    39  3118
   25   189    25    25     0     0
 1090    48   107  7438     0     0
  239   100   177     0     0     0
   33    66    24     0     0     0
  509     7    60     0     0     0
 3520    24     0     0     0     0
   40    25     0     0     0     0
   25   307     0     0     0     0
 1824     0     0     0     0     0
 1197     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 16x6]

(6,)
(6,)
......
before train torch.Size([16, 6])
before train torch.Size([16, 6])
[15 13 10  9  7  5]
after forward torch.Size([15, 6, 7615])
after forward torch.Size([16, 6])
Variable containing:
   21    25   341    62    25   438
   19    

(6,)
(6,)
......
before train torch.Size([18, 6])
before train torch.Size([18, 6])
[17 12  9  7  6  5]
after forward torch.Size([17, 6, 7615])
after forward torch.Size([18, 6])
Variable containing:
  502    25   341   355   223  1567
   14    50   148   398   100   656
    1   397   560    37    37  1339
   46    58    25   238    66   225
   18    25  1220    74  4803     0
   25   305   423   256     0     0
   50    18    74     0     0     0
  125     8    92     0     0     0
  112     1     0     0     0     0
   18    21     0     0     0     0
  502   627     0     0     0     0
   14     0     0     0     0     0
    1     0     0     0     0     0
 1132     0     0     0     0     0
 1133     0     0     0     0     0
 1134     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 18x6]

(6,)
(6,)
......
before train torch.Size([12, 6])
before train torch.Size([12, 6])
[11 10  9  7  6  6]
after forward torc

after forward torch.Size([14, 6, 7615])
after forward torch.Size([15, 6])
Variable containing:
    1   502    25   341   228    25
  320    14  1412  1301    24  5999
   74     1   353   355    60   198
  239  3625    37   737   277    37
   14    24   204    81    37     0
 3377    25    24   148   242     0
   17   778    60  1197     0     0
   58    74     0     0     0     0
   50    41     0     0     0     0
   18  1308     0     0     0     0
    8     0     0     0     0     0
  213     0     0     0     0     0
  112     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 15x6]

(6,)
(6,)
......
before train torch.Size([15, 6])
before train torch.Size([15, 6])
[14 13  9  7  7  6]
after forward torch.Size([14, 6, 7615])
after forward torch.Size([15, 6])
Variable containing:
   25     1   222    62   341  1105
   21  2442    70     7   148    73
  402    74     1    46   560    33
   25  2633   902     1   

after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
 5845   341  1571   355   341   276
   46   148  1572  3258   148   148
   70   560    18    43   560   702
 5500    85  1224    58    25    58
  373    24  1573    25  5220   198
  367    60  1308   188     0     0
   52   480    58     0     0     0
  126   152   762     0     0     0
   58   322     0     0     0     0
   25     0     0     0     0     0
  188     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 13x6]

(6,)
(6,)
......
before train torch.Size([14, 6])
before train torch.Size([14, 6])
[13  9  8  6  6  5]
after forward torch.Size([13, 6, 7615])
after forward torch.Size([14, 6])
Variable containing:
   62     1   215   341   341   249
 4351    62  4296   148   148    74
 1197   604  1687   560   560   686
   70    25  3502    25   215  1863
   25   337    24   633  6749     0
 4352    74    25     0   

after forward torch.Size([16, 6, 7615])
after forward torch.Size([17, 6])
Variable containing:
    1   341    91    62     1   341
   46   560    92    24    62   148
   24    25   815   189   413   560
    1  3030   816   190  3739    25
  370    74   817   164  1276   242
  287   426    24    66    37     0
   14    92    25   404  3740     0
 1302    24   110     0     0     0
    1  1456     0     0     0     0
 1303  1412     0     0     0     0
 1304     0     0     0     0     0
   24     0     0     0     0     0
  262     0     0     0     0     0
 1090     0     0     0     0     0
  239     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 17x6]

(6,)
(6,)
......
before train torch.Size([11, 6])
before train torch.Size([11, 6])
[10  9  9  8  7  6]
after forward torch.Size([10, 6, 7615])
after forward torch.Size([11, 6])
Variable containing:
 1467   651  1440   341     1    25
  288  4082    62   560   

after forward torch.Size([14, 6, 7615])
after forward torch.Size([15, 6])
Variable containing:
   50    25    25   341    25    25
  174   376  4397   560    42    50
 2653   433    24   686   440   169
    1    70  6904  1309  4189     1
   60   832   494    24    25   523
  373  4473   112  3085   552     0
   85  2405    37  2459     0     0
   15    40   200     0     0     0
   44   794   201     0     0     0
   25    24     0     0     0     0
  268  1456     0     0     0     0
 2727   504     0     0     0     0
  299     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 15x6]

(6,)
(6,)
......
before train torch.Size([15, 6])
before train torch.Size([15, 6])
[14  9  7  7  5  5]
after forward torch.Size([14, 6, 7615])
after forward torch.Size([15, 6])
Variable containing:
    1     1   107   370    21     7
  344  2066    36   450   310  1633
  587    74   148  1081     5    25
 1796   297   310    18   

after forward torch.Size([10, 6, 7615])
after forward torch.Size([11, 6])
Variable containing:
   57    25    50     1    25   124
 1863   108   397    62     7    37
   40   604   305   181   272    25
    1    25    58    55    25   242
  241   249   796    66   937     0
 1414    74   193   182     0     0
  363    25     0     0     0     0
   25   299     0     0     0     0
  744     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 11x6]

(6,)
(6,)
......
before train torch.Size([13, 6])
before train torch.Size([13, 6])
[12 11 11  9  6  5]
after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
   25    25   108    62    25   139
   62    50    24    24  1067   299
   24   125   189   189   422   300
   25    20   688    48   536   363
  370   152   592    19   817     0
  190    25    50   407     0     0
 3597  2977    18    25     0     0
   18   592   688   256   

before train torch.Size([12, 6])
before train torch.Size([12, 6])
[11  9  7  6  5  4]
after forward torch.Size([11, 6, 7615])
after forward torch.Size([12, 6])
Variable containing:
   25   297    25    46   697   177
 1590  6848    50    54    24   490
 3845  5012   445    62    37   691
   14   536    24   152    67     0
 2222  1303  6849   282     0     0
 6222    24  2275     0     0     0
  963  3085     0     0     0     0
 2202  3542     0     0     0     0
   20     0     0     0     0     0
  152     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 12x6]

(6,)
(6,)
......
before train torch.Size([11, 6])
before train torch.Size([11, 6])
[10  9  8  8  6  6]
after forward torch.Size([10, 6, 7615])
after forward torch.Size([11, 6])
Variable containing:
   25     1   166    57     1    46
   36    21    24   688   358   272
  367  2237   149    17    14    11
   28    25  1933    40   148    12
   18    84 

after forward torch.Size([19, 6])
Variable containing:
    1  1440    21  2349    25    91
  107    46    24    24  2362    92
   36    73   139   297  2363  6048
   24    33   190    18    58     0
    1    25   702   189     1     0
  355    99  3159    87   394     0
   18    18    23  2546     0     0
  149     8    74     0     0     0
   48    73   431     0     0     0
  100    23     0     0     0     0
 3254    37     0     0     0     0
   24     0     0     0     0     0
   25     0     0     0     0     0
  271     0     0     0     0     0
   37     0     0     0     0     0
   25     0     0     0     0     0
  552     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 19x6]

(6,)
(6,)
......
before train torch.Size([15, 6])
before train torch.Size([15, 6])
[14 11  9  9  8  5]
after forward torch.Size([14, 6, 7615])
after forward torch.Size([15, 6])
Variable containing:
 1467    11   341   107   305 

after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
   25    25    25     1    21    25
   85    21   331    67    70   108
  100  6365   142   742  1933   353
  509    84    25  1198    18    58
  101    19    71    25   149   860
    5    58    37   744  1621     0
   25    25    25     0     0     0
  825   188   282     0     0     0
   81    18     0     0     0     0
  634   226     0     0     0     0
 3015   246     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 13x6]

(6,)
(6,)
......
before train torch.Size([13, 6])
before train torch.Size([13, 6])
[12 11 10  7  6  4]
after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
 1456    25     1     1    25     1
 4765    67    21    60  5411   370
   37   125    70   153   702   698
 3863    66     1    14    58     0
  188     7   139   148   104     0
  673   246    63  2405   

after forward torch.Size([14, 6, 7615])
after forward torch.Size([15, 6])
Variable containing:
   62   306    25    25    21   223
   24   515    50    21   494   494
  139    90   445   310   112   246
   18  1578   305    58    18    58
  355    46    18  1019     8  1243
 1314    24     1    25   311    41
  190   355  6836    62    23    17
  367    62    14    37    17     0
   58    24   817    99     0     0
   50   818     0     0     0     0
   18     0     0     0     0     0
  584     0     0     0     0     0
  401     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 15x6]

(6,)
(6,)
......
before train torch.Size([25, 6])
before train torch.Size([25, 6])
[24 11 11 11  8  8]
after forward torch.Size([24, 6, 7615])
after forward torch.Size([25, 6])
Variable containing:
 1679     1    62  1469   341    25
  223   107    70   248   560    67
  152    36   189   277  2675   148
   25   324    63  1046   

after forward torch.Size([18, 6, 7615])
after forward torch.Size([19, 6])
Variable containing:
    1    36    25     1    25  1474
  241   213    62    62    85   148
   57    52   893    24   240    19
  604     7    25     1  1046     9
    1    17  5467    47    18   444
 1220    58   152   190   754     0
   57    52     7    39  1520     0
   18   458    58  2195   104     0
  656    40  2102     0     0     0
  682   624    18     0     0     0
  231    74    23     0     0     0
   76   917     0     0     0     0
  537     0     0     0     0     0
  651     0     0     0     0     0
 2619     0     0     0     0     0
  509     0     0     0     0     0
 2620     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 19x6]

(6,)
(6,)
......
before train torch.Size([10, 6])
before train torch.Size([10, 6])
[9 8 8 7 6 5]
after forward torch.Size([9, 6, 7615])
after forward torch.Size([10, 6])
Variable containin

(6,)
......
before train torch.Size([14, 6])
before train torch.Size([14, 6])
[13 11  7  6  6  3]
after forward torch.Size([13, 6, 7615])
after forward torch.Size([14, 6])
Variable containing:
   46     1     1   485     1   686
   70    62    62  1207   107   627
  459    24    19   486    36     0
  190     1    44    25     4     0
   37  1314    25    50   465     0
  132   190    36     0     0     0
  627    39     0     0     0     0
   40    58     0     0     0     0
   25    25     0     0     0     0
  238   305     0     0     0     0
   74     0     0     0     0     0
  256     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 14x6]

(6,)
(6,)
......
before train torch.Size([11, 6])
before train torch.Size([11, 6])
[10  7  7  7  6  6]
after forward torch.Size([10, 6, 7615])
after forward torch.Size([11, 6])
Variable containing:
   25     1   341   139   418     1
  107  1516   148   693  5192  1293


before train torch.Size([15, 6])
before train torch.Size([15, 6])
[14 10  9  9  9  5]
after forward torch.Size([14, 6, 7615])
after forward torch.Size([15, 6])
Variable containing:
   50    11     1     1    25   755
  445  3203    36    60    92   756
   24    21   584  1947    70   486
   58   688    25   299   139   363
  796  1887   231    14  1491     0
    1   246    74   761    89     0
   62    52    25    24     9     0
   44   188   523   618   308     0
   25   351     0     0     0     0
 1494     0     0     0     0     0
  737     0     0     0     0     0
 2627     0     0     0     0     0
   41     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 15x6]

(6,)
(6,)
......
before train torch.Size([12, 6])
before train torch.Size([12, 6])
[11  9  8  7  7  4]
after forward torch.Size([11, 6, 7615])
after forward torch.Size([12, 6])
Variable containing:
   50     1  1440    25    25   189
  397    46 

before train torch.Size([9, 6])
before train torch.Size([9, 6])
[8 7 7 6 6 6]
after forward torch.Size([8, 6, 7615])
after forward torch.Size([9, 6])
Variable containing:
   25   341   148     1    21    36
   50   560  1197   189    24   750
  445    25    25   221  1244     5
   24  4442  1125    14   353    25
    9    18  6806  2405   911  1674
   25  3299    55     0     0     0
   99     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 9x6]

(6,)
(6,)
......
before train torch.Size([12, 6])
before train torch.Size([12, 6])
[11  9  8  7  6  5]
after forward torch.Size([11, 6, 7615])
after forward torch.Size([12, 6])
Variable containing:
   25   794    25  2112   148    25
   85   217   768   413  3040    42
  100  1623    14    28  2818   148
   25   509  3864    81     4   125
  297   404    58   148   112     0
   71    81    25  1197     0     0
   37   148   110     0     0     0
   25  1197     0     0

after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
  341   148     1     1    85    25
  560  1197   322    50   148   321
   25   341    74  1125    82    19
 5093   560    92  1353   145    58
   74    25   536   152    33    25
   25  2173   257    25    74  1375
   45   380   277   505  1224     0
   81  1270    22     0     0     0
   25    28     0     0     0     0
  148     0     0     0     0     0
 1197     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 13x6]

(6,)
(6,)
......
before train torch.Size([13, 6])
before train torch.Size([13, 6])
[12 12 11  9  7  7]
after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
   25     1   235  1440   107  1440
   61    46    14    46    36    62
  893    24   148    14    69   636
  152   189  4460   257    70     5
   25    19    37   761   370     1
  355    90    25    24   

after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
  177   132   148    25   334   313
  987   486  1197    21   702    24
   37     1   341   702    58    25
  107    62   560    58  1246   399
   36    37     1   515  1412     0
   24   305   299     0     0     0
  370   588   715     0     0     0
  190     1    90     0     0     0
  888    60     0     0     0     0
   82   905     0     0     0     0
   33     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 13x6]

(6,)
(6,)
......
before train torch.Size([15, 6])
before train torch.Size([15, 6])
[14 11  9  7  6  5]
after forward torch.Size([14, 6, 7615])
after forward torch.Size([15, 6])
Variable containing:
   25    25   139   200   177  3170
 2349    67   436    57   353  2733
   14   174    43    14  3043   339
 1232   181   363    37    25   661
  152    66  1240    60   325     0
   25   182    37   390   

after forward torch.Size([13, 6, 7615])
after forward torch.Size([14, 6])
Variable containing:
   25    62    25    25  1694  3714
   21    37    21    67   166    14
   24    99   754  1212   148  6171
  189   367     1   374   125    58
   19    58  2555   145    52   869
   58  1998    37    37   188     5
   25   305    25    25     7    84
   95    18  2013   747     0     0
  673   353     0     0     0     0
   74    58     0     0     0     0
   25    19     0     0     0     0
  390     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 14x6]

(6,)
(6,)
......
before train torch.Size([14, 6])
before train torch.Size([14, 6])
[13 12  8  7  7  6]
after forward torch.Size([13, 6, 7615])
after forward torch.Size([14, 6])
Variable containing:
   25   502  2675    25    25   166
  797    14   536    50    57    87
  256     1  2405   397    73    40
   37    21    81    17     5    25
 3863    37    25    58   

after forward torch.Size([14, 6, 7615])
after forward torch.Size([15, 6])
Variable containing:
   36   148    46  1914  3710     0
   24  1197    70  1530  1353     0
  139   341   902   310  1686     0
  376   560   148     5     0     0
   18    25   367   308     0     0
  355  3820    28     0     0     0
  520     0     0     0     0     0
   43     0     0     0     0     0
   58     0     0     0     0     0
   25     0     0     0     0     0
  305     0     0     0     0     0
   33     0     0     0     0     0
  256     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 15x6]

(6,)
(6,)
......
before train torch.Size([16, 6])
before train torch.Size([16, 6])
[15 12  8  7  6  5]
after forward torch.Size([15, 6, 7615])
after forward torch.Size([16, 6])
Variable containing:
   11    62    25     1    25    91
  768    40    50   797   563  1737
   19    25   367   214    14  1285
  152   859   305   125   

[12 10  8  8  6  6]
after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
   21    25     1   513  1505    91
   24  1220    67    37     4    92
  297    36   191   153    23   761
  356    39    18    14    58     1
   18   631   993    24   149   438
  189    40   651  1456     0     0
  808    25   404  1412     0     0
  627  1560     0     0     0     0
   81    36     0     0     0     0
  148     0     0     0     0     0
 1197     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 13x6]

(6,)
(6,)
......
before train torch.Size([13, 6])
before train torch.Size([13, 6])
[12 11  9  9  6  6]
after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
  341    62   502   148    21    25
 1200    24    14  1197    24  4507
  112   297     1   341   139   178
   40    19   503   228    19    11
   25    17   242   441    44  4777
 3036 

after forward torch.Size([11, 6, 7615])
after forward torch.Size([12, 6])
Variable containing:
  341    62    91    25    25    50
 1686  1248   728    21   686   445
  560   112   536    19    14    24
  228    25  1780    20  3089  1687
   37  6646    25   152    81     0
   25    74   317    25     1     0
  188  1538   292   633   977     0
   74  1932     1   644  1694     0
   25   153   337     0     0     0
 1412     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 12x6]

(6,)
(6,)
......
before train torch.Size([15, 6])
before train torch.Size([15, 6])
[14  8  7  6  5  5]
after forward torch.Size([14, 6, 7615])
after forward torch.Size([15, 6])
Variable containing:
 1791     1     1   177    92     1
   57   107    21    82  2369    71
 1794   108   125    33   152   940
  734  3383    44    25   308  1358
  688   292    25    63     0     0
   17     1   532     0     0     0
   76   691     0     0   


(6,)
(6,)
......
before train torch.Size([11, 6])
before train torch.Size([11, 6])
[10  9  9  8  6  5]
after forward torch.Size([10, 6, 7615])
after forward torch.Size([11, 6])
Variable containing:
  268   223     1     1     1    25
 1336    40     7   633   998  6298
  486   624    51   644   993    46
   24  1212    24    24    66    49
  249  1685    58     1   638     0
   74    55  2902  4509     0     0
  686  1708     1  1357     0     0
   37  4991   926     0     0     0
   25     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 11x6]

(6,)
(6,)
......
before train torch.Size([12, 6])
before train torch.Size([12, 6])
[11 10  9  8  7  6]
after forward torch.Size([11, 6, 7615])
after forward torch.Size([12, 6])
Variable containing:
   25    21    25    62    62  2726
   50    24    46   486   893   963
  125   355    24    91   200     1
   58   160    60    92    61  2727
   25    24    14    24    81 

after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
   25    25    25    46    25     0
   62    35   108   148  6676     0
  324    36   688   100    14     0
   17    24    58     7  1848     0
   25  2764    66   246  1962     0
 2094    14   188  2680     0     0
   18  3726     0     0     0     0
   19    37     0     0     0     0
   20    25     0     0     0     0
   70  2094     0     0     0     0
  187     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 13x6]

(6,)
(6,)
......
before train torch.Size([9, 6])
before train torch.Size([9, 6])
[8 8 6 6 5 5]
after forward torch.Size([8, 6, 7615])
after forward torch.Size([9, 6])
Variable containing:
   50     1    62     1    62   334
  445    21    24    62   122    14
   24    24   189   798  5332   148
   81   149   604    66    55   817
   25   310    99   126     0     0
  148     5     0     0     0     0


after forward torch.Size([16, 6, 7615])
after forward torch.Size([17, 6])
Variable containing:
   25    25     1  2857     1    25
  188    62    60    74  1736  3706
  380    24    18   250   627    87
   74   189   139    45  2300    66
   25    14   221    14    25     7
   21   212    14   257  1572     0
 1358    58  2755     0     0     0
    4  3605     0     0     0     0
   24     0     0     0     0     0
   25     0     0     0     0     0
  782     0     0     0     0     0
   81     0     0     0     0     0
   25     0     0     0     0     0
  344     0     0     0     0     0
 1197     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 17x6]

(6,)
(6,)
......
before train torch.Size([12, 6])
before train torch.Size([12, 6])
[11 10  9  9  7  6]
after forward torch.Size([11, 6, 7615])
after forward torch.Size([12, 6])
Variable containing:
  721    25     1    62  1961    25
 5195    21   108   134   

after forward torch.Size([11, 6, 7615])
after forward torch.Size([12, 6])
Variable containing:
   21  1165    36    50   438  2617
   86  1189    24   445   310   246
   50  1386    23    24    24     1
  445   214   657    37   152  1549
   24  3336   101    25   188    74
   37    24    37   461  1275   110
   92    25  3309   845  4233     0
 1510  2767     0     0     0     0
  363   305     0     0     0     0
 2173     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 12x6]

(6,)
(6,)
......
before train torch.Size([10, 6])
before train torch.Size([10, 6])
[9 8 7 6 4 4]
after forward torch.Size([9, 6, 7615])
after forward torch.Size([10, 6])
Variable containing:
  341    57    25    91    57    50
 1301     4  2271    92   993   445
   25   348   362   339    61    55
  148   242   112   721     0     0
   45    81    25   377     0     0
  880   148   602     0     0     0
  127  1197     0     0     0    

after forward torch.Size([8, 6, 7615])
after forward torch.Size([9, 6])
Variable containing:
   99     1    62   652    25  1353
 1398     7    24    77  2166     0
 2070  2035    60    25    14     0
  152    25    14    61   817     0
  149  2200   817     0     0     0
   58     0     0     0     0     0
   60     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 9x6]

(6,)
(6,)
......
before train torch.Size([10, 6])
before train torch.Size([10, 6])
[9 8 7 6 6 4]
after forward torch.Size([9, 6, 7615])
after forward torch.Size([10, 6])
Variable containing:
 3966   341     1  1500   108    62
  815   560    67    24    24   353
  816    25   272    60   189   147
  817  6378    24  1017   546     0
   81    37    25   337   406     0
   25    25   782     0     0     0
  148   378     0     0     0     0
 1197     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0


after forward torch.Size([10, 6, 7615])
after forward torch.Size([11, 6])
Variable containing:
  108    25   370     1    25     1
   24  1125   989   503  1923   241
  370  3225   221   242    14   787
  688  4754    14    14  1520   169
  246    81   148   257  2405    17
   66    25   817     0     0     0
  351   148     0     0     0     0
   40  1197     0     0     0     0
   50     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 11x6]

(6,)
(6,)
......
before train torch.Size([12, 6])
before train torch.Size([12, 6])
[11 11  9  7  7  5]
after forward torch.Size([11, 6, 7615])
after forward torch.Size([12, 6])
Variable containing:
   25    25    25     1     1    62
   50    60    67  3180     7   212
  397  2342    14   153   627    49
   58   296   565   178    24  1686
   11   105    20    11    25     0
   12    25   152  4777  2079     0
  256  1072    25     0     0     0
   37    74    50     0   

......
before train torch.Size([15, 6])
before train torch.Size([15, 6])
[14 10 10 10  6  4]
after forward torch.Size([14, 6, 7615])
after forward torch.Size([15, 6])
Variable containing:
  341    11    36    25   148    50
  560   971    24   438  3835   397
 1428    62   149    14    74   188
  688    19   151    24   411     0
 1708   112    36    25  1685     0
    1  2811    24  1639     0     0
 1822   592   189    74     0     0
   74    25   207    25     0     0
  687  2812  3438  1412     0     0
   24     0     0     0     0     0
 3085     0     0     0     0     0
   91     0     0     0     0     0
 3542     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 15x6]

(6,)
(6,)
......
before train torch.Size([17, 6])
before train torch.Size([17, 6])
[16 12  8  7  6  5]
after forward torch.Size([16, 6, 7615])
after forward torch.Size([17, 6])
Variable containing:
    1    62    25    25   687  2431
   62


(6,)
(6,)
......
before train torch.Size([10, 6])
before train torch.Size([10, 6])
[9 8 7 6 6 6]
after forward torch.Size([9, 6, 7615])
after forward torch.Size([10, 6])
Variable containing:
   25    25     1    67    25    25
  399    57   788   688    67    92
   16     4   815    40  1017  2546
 2634   152   816    52    66    25
   18   277   817     7   145  2372
    8    58   562     0     0     0
  234    15     0     0     0     0
  641     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 10x6]

(6,)
(6,)
......
before train torch.Size([12, 6])
before train torch.Size([12, 6])
[11 10  9  8  6  4]
after forward torch.Size([11, 6, 7615])
after forward torch.Size([12, 6])
Variable containing:
  148    25    46    25   555    21
 1197    36    24    50   354  2525
  322    37   189   486   191  1088
  754    25   218     1   509     0
    1   305    41  1549   101     0
 1358   178    24    74     0     0
 

after forward torch.Size([10, 6, 7615])
after forward torch.Size([11, 6])
Variable containing:
   99     1    21    25    25    46
 1398    57    24  1539    57   353
  148  2627   355  1562   367    58
  198    25   499   112    28   463
   58    50   112     0     0     0
   60   385   685     0     0     0
   18   187     0     0     0     0
    8    43     0     0     0     0
  189    33     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 11x6]

(6,)
(6,)
......
before train torch.Size([9, 6])
before train torch.Size([9, 6])
[8 8 7 7 6 5]
after forward torch.Size([8, 6, 7615])
after forward torch.Size([9, 6])
Variable containing:
    1   139   900    25  1440    21
  127  6730   367    42   355    19
   17   536    18    32  2423  4336
   74   817  1263    33   486  6620
   25    81  3285    25   363     0
  768   148  1686  1624     0     0
 1114  1197     0     0     0     0
    0     0     0     0     0     0


after forward torch.Size([18, 6, 7615])
after forward torch.Size([19, 6])
Variable containing:
   67    57    25    36   610     1
  750    24    50    24    58    46
   17    23   445   149  2257    24
    1   353    24   367    55   167
  330    58    37    58    25   627
   40   515    25   515   633     0
   25    55   621    20     0     0
 1824   848     0     0     0     0
 1197   367     0     0     0     0
  748    28     0     0     0     0
  177    18     0     0     0     0
  272   310     0     0     0     0
    1    23     0     0     0     0
   71     0     0     0     0     0
   18     0     0     0     0     0
   43     0     0     0     0     0
   33     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 19x6]

(6,)
(6,)
......
before train torch.Size([14, 6])
before train torch.Size([14, 6])
[13  9  8  7  5  5]
after forward torch.Size([13, 6, 7615])
after forward torch.Size([14, 6])
Variable co

after forward torch.Size([13, 6, 7615])
after forward torch.Size([14, 6])
Variable containing:
    1    62  1440    25   341    46
  241   311    67   148   148   688
  370    17   100   299   560    40
   42    18     1    58    11    25
  441   100   797  1301  1003    50
   70    66  1660    37     0     0
    1   101    24    25     0     0
  379    37    66   305     0     0
    7    66   145     0     0     0
   37   102     0     0     0     0
   25     0     0     0     0     0
  378     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 14x6]

(6,)
(6,)
......
before train torch.Size([9, 6])
before train torch.Size([9, 6])
[8 8 7 6 6 6]
after forward torch.Size([8, 6, 7615])
after forward torch.Size([9, 6])
Variable containing:
   25    62   560  1575    50     1
   21   196   139    37   445  4089
  413   404  2747   659    24   310
   25    17    74   536    37     5
  432    24    25  2405    99   308


after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
   91   341    62    92   177    57
  991   536    24  1301    70   218
 3550  4911   717    94    60   403
    1    58   148    95   373  2123
 5846     1   627    37   148     0
  629   344   127     1   257     0
 6459   190    17  2297     0     0
 6460     0     0     0     0     0
   74     0     0     0     0     0
  215     0     0     0     0     0
 4196     0     0     0     0     0
    0     0     0     0     0     0
    0     0     0     0     0     0
[torch.LongTensor of size 13x6]

(6,)
(6,)
......
before train torch.Size([13, 6])
before train torch.Size([13, 6])
[12  8  7  7  6  4]
after forward torch.Size([12, 6, 7615])
after forward torch.Size([13, 6])
Variable containing:
   25     1    25    36    25    25
  119    21    62   993  1355   643
 4666    70    51   370  1198   702
  550     1   112    71   536     0
  480  3084    81    58  2405     0
   37    19    41   378   

In [ ]:
#for i, data in enumerate(trainloader,0):
#    print(i)